import {Roboto_Serif } from "next/font/google";
import "./globals.css";
import Navber from "@/componets/Navber";
import Footer from "@/componets/Footer";
import { ToastContainer } from "react-toastify";
import { Toaster } from "react-hot-toast";




const jus =Roboto_Serif ({

  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${jus.className}} h-full antialiased`}
    >
      <body className={`${jus.className} min-h-full flex flex-col  bg-gradient-to-br from-black via-slate-900 to-sky-950`}>
        <ToastContainer />
        <Navber></Navber>
        {children}
       <Footer></Footer>
         <Toaster />
        </body>
    </html>
  );
}
